baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nisanth Kennath'
theme = 'hugo-paper'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'nishken92'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'nishken92'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = '/public/flash.png.jpg'                 # gravatar email or image url
  name = 'NISANTH KENNATH'
  bio = 'Senior Software Engineer | Telecom Mediation | Product Support | Service Delivery | AI Ops | FOSS Enthusiast | Hobbyist Content Creator'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  #monoDarkIcon = true                       # show monochrome dark mode icon
  #gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  #graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  direction = "ltr"                         # RTL support for Right-to-left languages

